gkjohnson/three-mesh-bvh

example/index.bundle.js
example/index.js
index.js
lib/GeometryUtilities.js
lib/IntersectionUtilities.js
lib/MeshBVH.js
package.json

- Added option to check only first hit by changing the raycaster intersectObject[s] calls. So 
`const res = raycaster.intersectObject(containerObj, true);`
gets all intersections and
`const res = raycaster.intersectObject(containerObj, true, null, true);`
stops after the first intersection.
- Removes duplicate intersections when getting all intersections so the result matches what you'd get from the default raycaster. Duplicates showed up because the same face can show up in multiple nodes, so I keep track of which faces have been checked already. (While i was at it I changed the faceIndex to match the latest changes in Three since it wasn't unique before)

Remove duplicate intersections and Add option for only first hit

---

lib/GeometryUtilities.js

This was the lowest-hanging optimization fruit I found without really sacrificing any readability yet -- reduces tree construction time by roughly 10% on my Firefox.

Speed up some triangle math hotspots

---

lib/BoundsUtilities.js
lib/MeshBVH.js
lib/MeshBVHNode.js

Save memory by storing the box and sphere bounds data in a Float32Array of 7 values:
```
0: sphere radius
1, 2, 3: bounds center
4, 5, 6: half box extents
```
The change also sets `children` to null by default.
Here's the benchmark data. The torus knot was generated with the following parameters:
`const geometry = new THREE.TorusBufferGeometry( 5, 5, 400, 100 );`
Benchmarks on master:
```
Compute Bounds Tree      : 395.25 ms
Default Raycast          : 5.065767 ms
BVH Raycast              : 1.157732 ms
First Hit Raycast        : 0.147442 ms
Memory Usage             : 22870.854 kb
```
Benchmarks on this branch:
```
Compute Bounds Tree      : 381.375 ms
Default Raycast          : 4.957096 ms
BVH Raycast              : 1.136364 ms
First Hit Raycast        : 0.143314 ms
Memory Usage …
```

Store bounds info in a Float32Array

---

lib/MeshBVHVisualizer.js

Self-explanatory, this broke with the recent changes to `MeshBVHNode`.

Bring visualizer up to date with mesh node structure

---

lib/MeshBVH.js

Self-explanatory. The averaging was the substantial part which is nice to avoid if we don't need to do it. No big deal, though -- it shaves off maybe just a few percent on the benchmark in tree construction for the CENTER strategy:
```
Compute Bounds Tree      : 36.22 ms
Default Raycast          : 1.753361 ms
BVH Raycast              : 0.183453 ms
First Hit Raycast        : 0.099249 ms
Total Memory Usage       : 2633.052 kb
Geometry Memory Usage    : 1134.216 kb
Bounds Tree Memory Usage : 1498.836 kb
```

Don't do work for split strategies we aren't using

---

src/BVHConstructionContext.js
src/BoundsUtilities.js
src/GeometryUtilities.js
src/MeshBVH.js

Pretty self-explanatory. This really moves the needle on the AVERAGE strategy, but even for CENTER it shaves off a percentage point or two on tree construction time (much easier to see with the new larger benchmark.)

Don't do extra work when splitting

---

src/MeshBVHNode.js

@mquander 
This optimizes the `raycastFirst` path to speed things up a bit. The big change is only checking the ray along the split axis to decide if we should return the c1 intersection result. This means we don't always do a full c2 bounds check when the correct result is in the first child. With this change I'm back up to the as-advertised 500 intersections at 60fps in the readme (on my machine, at least...)
Here are the benchmarks:
*Before*
```
First Hit Raycast        : 0.10469 ms
```
*After*
```
First Hit Raycast        : 0.02901 ms
```
Fix #38

Raycast first optimization

---

package.json

`name` is required in order for people to install this via NPM.

Add and fix metadata on package.json

---

src/BVHConstructionContext.js

1. When zipping through the things on the left and right side of the range that were already in the correct order with respect to the split plane, we weren't checking the range bounds. That means that if we made a really terrible split, such that all the triangles are on one side, it could go "off the end", do an arbitrary amount of extra work, and return an invalid left index. This caused #53.
2. At the end of the partitioning, we would tend to do one unnecessary swap. Now we don't.
This doesn't seem like it impacts performance much. I guess you would expect it to be a tiny bit slower on typical geometries on accounts of the bounds checks.

Fix bugs in partition

---

src/BVHConstructionContext.js
src/MeshBVH.js

It doesn't seem to me like we had any reason to intersect the new bounds with the bounds of the parent -- since the triangles in the child are a subset of the triangles in the parent, it seems patently impossible for the child bounds to not already be a subset of the parent bounds.

Don't do extra work to generate child node bounds

---

src/MeshBVH.js

Addresses something I mentioned in #51 -- previously, if we reached the maximum depth, we would do a final split + partition and then predictably throw out the result and turn the node into a leaf. So let's not do that extra work.

Move depth check to top of splitNode

---

src/GeometryUtilities.js

Since we now create an index as a side effect of constructing the tree, we don't need to have a separate branch for non-indexed geometries any more when raycasting.

Raycasting code can presume indexed geometry

---

README.md
rollup.config.js

Rename the global UMD variable from `MeshBVH` to `MeshBVHLib`, as discussed [here](https://github.com/gkjohnson/three-mesh-bvh/pull/60#discussion_r244400200).

Rename the global umd variable `MeshBVH` to `MeshBVHLib`

---

src/MeshBVH.js
src/MeshBVHNode.js
src/MeshBVHVisualizer.js
test/test.js

This doesn't really move the needle in a measurable way for me on the benchmark, but it's very easy to do and nice to make the resulting tree more memory-efficient.
In Chrome, taking a heap snapshot of the example page, the tree size before this change is 6617152 bytes, and the tree size after this change is 581236 bytes.

Store left, right instead of children array

---

package-lock.json
package.json

Just bringing this up to date so that I don't have to be suspicious that the old three.js version is fooling me somehow. Tested that the example page continues to work correctly.

Bump dev version of three.js

---

src/MeshBVH.js
src/index.js
test/test.js

Resolves #66. Now the BVH respects [groups](https://threejs.org/docs/#api/en/core/BufferGeometry.groups) on geometries, instead of mucking up the index and rendering the groups meaningless. This implements "option 3" as discussed in the linked issue. It seems to work well on some test Hubs scenes that have geometries with groups. There's no measurable change in performance for geometries that don't have groups, as it just adds one trivial layer of processing and indirection at the top of raycasting.

Support building BVH for geometries with material groups

---

CHANGELOG.md
README.md
src/MeshBVH.js
test/test.js

Fix #72.
Pretty basic PR that adds errors if `InterleavedAttributeBuffers` are used and updates the docs. If all looks good I'll plan to push `v0.1.0`. I think I'll leave #71 until there's a better use case for its inclusion.

Add Error Conditions and Update Docs

---

src/MeshBVH.js
src/MeshBVHVisualizer.js
test/MeshBVH.test.js

Fix #75
Fix #94
Related to #93 
- Add a test to verify that the correct array type is used for the index buffer
- Fix case where the index buffer would be instantiated with the wrong type
- Make the MeshBVHVisualizer work with multiple BVH roots

Fix created index array, visualizer

---

src/MeshBVH.js

Resolves #101. This seems to be as polite as it's possible to be with respect to the geometry's bounding box.
It's annoying to have to branch for the one-root and many-roots case, but I can't think of any obviously better way to rearrange it. We could make it a little cleaner by fiddling around with the top of the tree structure, but I can't say I endorse any particular change.

Reuse and/or populate Geometry.boundingBox

---

package.json

I've been getting this warning message for a while now:
```
warning " > three-mesh-bvh@0.1.3" has incorrect peer dependency "three@^0.102.1"
```
So I figured I'd update the peer dependency version for three. Let me know if it should be something else.

Fix three peer dependency version

---

README.md
benchmark/run-benchmark.js
benchmark/utils.js
src/BVHConstructionContext.js
src/Utils/Debug.js
src/index.js

Improve the benchmark output to better show the performance differences between strategies and move some util benchmark functions into the library exports for debugging. Related to #121 to understand the behavior.
New benchmark output looks like
```
*Strategy: CENTER*
Extremes:
memory: 9755.746 kb
tris: 1, 151
depth: 11, 22
splits: 20697, 21638, 12472
Compute BVH              : 108.785714 ms
BVH Raycast              : 0.687916 ms
First Hit Raycast        : 0.100817 ms
IntersectsSphere         : 0.013736 ms
IntersectsBox            : 0.00089 ms
DistanceToGeometry       : 2529 ms
DistanceToPoint          : 0.203555 ms
IntersectsGeometry with BVH: 16.347826 ms
IntersectsGeometry without BVH: 895.5 ms
*Strategy: AVERAGE*
Extremes:
memory: 9362.722 kb
tris: 1, 151
depth: 11, 18
splits: 21259, …
```

Improve Benchmark Output

---

src/BVHConstructionContext.js

Removed use of "Math.min" and "Math.max".
Benchmark for CENTER Before:
```
Compute BVH              : 106.275862 ms
```
Benchmark for CENTER After:
```
Compute BVH              : 94.125 ms
```

Small performance improvement to "getBounds"

---

src/BVHConstructionContext.js
src/MeshBVH.js

Fix #121
Improves the CENTER split method by picking the center of the centroid bounds along the longest axis rather than the center of the node bounds to partition against. This fixes cases like in #121 where you might have a node that winds up containing tens of thousands of triangles because a naive CENTER split of the node doesn't effectively divide the triangles and quit traversing.
The triangle centroid bounds are computed in the same pass as the node bounding box to avoid redundant array accesses. This minimizes the overhead of generating the centroid bounds and along with the improvements from #126 there is basically no performance degradation in computing the BVH compared to the last v0.1.5 release.
Here are the significant benchmark comparisions relative to master (including …

Improve CENTER split raycast performance

---

benchmark/run-benchmark.js
src/MeshBVH.js
src/MeshBVHNode.js
src/Utils/Debug.js
test/MeshBVH.test.js

Fix #7 
Related to #42
Adds a serialization and deserialization function to the BVH which should allow it to be generated in a webworker. The serialized data is currently formatted as follows with 36 bytes per node:
```js
{
roots: Array<ArrayBuffer>,
index: UInt32Array
}
```
```
Extremes:
memory: 10517.93 kb
serialized: 4254.446 kb
tris: 1, 10
depth: 11, 22
splits: 24087, 24086, 10916
Compute BVH              : 123.16 ms
Serialize                : 14.88 ms
Deserialize              : 34.68 ms
```

Add serialization and deserialization of bvh

---

package.json
scripts/generate-cast-functions.js
scripts/generate-cast-functions.mjs
src/MeshBVH.js
src/MeshBVHVisualizer.js
src/Utils/Debug.js
src/Utils/ThreeIntersectionUtilities.js
src/Utils/TriangleUtils.js
src/buildFunctions.js
src/castFunctions.js
src/castFunctionsBuffer.js
test/IntersectionUtils.test.js
test/MeshBVH.test.js
test/RandomRaycasts.test.js

Fix #42
- Move `intersectsBox`, `intersectsSphere`, `closestPointToPoint`, `closestPointToGeometry` logic to `MeshBVH`.
- Clean up `castFunctions` to make it more processable.
- Add generation script to convert `castFunctions.js` into packed buffer variants.
- Add buffer branch in the cast functions.
**TODO**

Add 'packData' option to improve memory footprint

---

src/MeshBVHDebug.js
src/buildFunctions.js
src/index.js
test/MeshBVH.test.js

Fix #169
~PR expands the leaf bounds by the amount of floating point precision loss when converting the bounds' center and half extents to 32 bit floats. At most the difference seems to be `0.00001526`.~
~The other option is to store the min and max bounds rather than the center and half extents which would  prevent an precision issues all together. The center value is used in a variety of functions, though, so performance would have to be compared.~
~Benchmark for creating a BVH goes up by \~10ms from `~144ms` to `~157ms`.~
Adds an epsilon value to the half extents to ensure the new bounds still encapsulates all contents after float32 conversion.

Bounds containment fix

---

README.md
example/collectTriangles.js
scripts/generate-cast-functions.js
src/Constants.js
src/castFunctions.js
src/castFunctionsBuffer.js
src/index.js
test/ShapeCasts.test.js

Fix #104
Fix #84 
Add shapecast optimization if an object is reported to be contained so we can stop traversal early and iterate over all contained triangles.
- Add lasso example

Add shapecast contains optimization

---

README.md
example/selection.js
scripts/generate-cast-functions.js
src/castFunctions.js
src/castFunctionsBuffer.js

Related to #99
- Add depth argument
- Use the depth argument in the lasso example to improve performance
- Shapecast cannot be called in a nested way (enable passing a cached bounds and triangle in)

Add depth parameter to shapecast callbacks

---

README.md

I guess it was not intended, the snippets in your readme import the modules without `from` : 
```js
import { MeshBVH, acceleratedRaycast } 'three-mesh-bvh';
```

add 'from' in snippets in readme

---

example/characterMovement.js
package.json
src/Utils/ThreeIntersectionUtilities.js

Related to #189 
Related to the last changes in threejs r0.125.x [(Migration Guide r125 -> r126)](https://github.com/mrdoob/three.js/wiki/Migration-Guide#r125--r126)
Replaces Face3 class with an object, because it is now unsupported in r0.125.x.

Unsupported Face3 dependency was replaced

---

README.md
benchmark/run-benchmark.js
scripts/generate-cast-functions.js
src/MeshBVH.js
src/Utils/Debug.js
src/buildFunctions.js
src/castFunctions.js
src/castFunctionsBuffer.js
test/MeshBVH.test.js
test/RandomRaycasts.test.js
test/RandomRaycastsRepro.test.js
test/ShapeCasts.test.js

Remove lazyGeneration option

---

rollup.config.js

Related discussion: https://discourse.threejs.org/t/three-mesh-bvh-a-plugin-for-fast-geometry-raycasting-and-spatial-queries/26394/2
This will add a `esm` ( module ) bundle file to `./esm/index.js` after run `npm run build`.
In my current project's specific case, I need change 
`import ... from 'three';` to
`import ... from './three/build/three.module.js';` after build.
But I think I can't hard-code the url of three.js.
Is it acceptable to leave `import ... from 'three';` as is and let user to change the url afterwards?

Add `esm` ( module ) build output.

---

README.md
src/MeshBVH.js
src/MeshBVHVisualizer.js
src/Utils/ThreeIntersectionUtilities.js
src/castFunctions.template.js

Fix #269 
- Fix first hit raycast not returning the correct result when the model transform has been adjusted.
- Add `opacity`, `color` fields to MeshBVHVisualizer.
**TODO**

World space raycast first fix

---

example/clippedEdges.js

- Add dynamic draw usage for outlines
**TODO**
- Use "CONTAIN" to determine whether or not to try plane intersection
- May require specifying that `intersectsBounds` is guaranteed to be run immediately before `intersectsTriangle` so we know whether the specified range is known to be contained or not.

Update clippedEdges demo

---

README.md
src/core/castFunctions.js
test/ShapeCasts.test.js

Fix #313 
- Add use of box pool so recursive shapecast use will not cause collisions
- Add box to intersectsRange function

Shapecast: add use of box pool

---

src/core/MeshBVH.js
src/core/bvhcast.js
src/debug/Debug.js
src/objects/MeshBVHVisualizer.js
src/utils/ExtensionUtilities.js
src/utils/ThreeRayIntersectUtilities.js

To help enable tree shaking, though in practice the MeshBVH class is probably  too monolithic at the moment to enable it effectively.

add /* @__PURE__ */ identifiers

---

README.md
benchmark/run-benchmark.js
src/core/MeshBVH.js
src/index.js
src/utils/TriangleUtilities.js
test/ShapeCasts.test.js

fixes #318, #321 
I've made the changes described in the mentioned issues: Target parameters can be Vector3 (as before), or objects (either ```{ }``` or the object from a previous execution). The objects (if not null) are filled with face indices, normal, uv, etc.
For ```closestPointToGeometry``` I've made it return always the info for target1 (```this.geometry```), but target2 (related to otherGeometry) is updated if it is an object. Mixing Vector3 and info object for target1 and target2 is not suported.
Also I've removed the ```distanceToPoint``` and ```distanceToGeometry``` functions of ```MeshBVH```.
The code has become large, let me know if there is something you would remove/modify.
Edit: Forgot to mention I've run the tests and they work fine. But the benchmark seems not to work, …

Make MeshBVH.closestPointToPoint, closestPointToGeometry return more info

---

README.md
src/utils/TriangleUtilities.js

Related to #325
Extracts the material index in the `getTriangleHitPointInfo` using the geometry group ranges.

getTriangleHitPointInfo: Extract material index correctly

---

babel.config.json
example/cpuPathTracing.html
example/cpuPathTracing.js
example/pathtracing/ggxSampling.js
example/pathtracing/materialSampling.js
example/pathtracing/utils.js
package-lock.json
package.json
src/workers/GenerateMeshBVHWorker.js

Related to #291 
**TODO**
- hits diffuse surface at high reflectance spot, then specular surface which hits light directly
- accumulate a roughness to use -- use max roughness found during traversal? Or some scaling factor of it
- See discussion on Blender's solution [here](https://github.com/hoverinc/ray-tracing-renderer/issues/12#issuecomment-531613711)
- Determine if a ray is "rough" based on its dot from the perfect specular ray b/c even if a surface is smooth there are still diffuse rays that get used
- Switch to use just diffuse / specular for debugging
- Switch to use the approach to divide out the PDF initially then handle both diffuse and specular together
- https://learnopengl.com/PBR/Theory
- https://graphics.stanford.edu/courses/cs348b-01/course29.hanrahan.pdf
**ISSUES**
**TO …

CPU Path Tracing Example

---

src/core/MeshBVH.js
src/index.d.ts
test/ShapeCasts.test.js

* Takes into account otherBvh.gomeotry in the bvhcast function
* Adds few tests to be sure triangles are iterated
* Fixed the typescript definitions about bvhcast function callbacks
*  _callbacks_ param cannot be decomposed if undefined
* Seems like the intersectsTriangles callback is required (otherwise intersectsRanges function can be null when called [here](https://github.com/minitoine/three-mesh-bvh/blob/76e6b68644f50269088add617a4bd294fcbbf1c6/src/core/MeshBVH.js#L677)

Fix issue #368

---

src/gpu/VertexAttributeTexture.js
test/VertexAttributeTexture.test.js

fix #372 
cc @arpu Sorry this turned out to be more complicated than I anticipated but this should remove the use of RGBFormat from the project. GPU path tracing demos and tests have been been tested here.
**TODO**
- Remove `RGBIntegerType`

VertexAttributeTexture: Remove use of RGBFormat

---

src/core/buildFunctions.js
src/workers/generateAsync.worker.js
test/MeshBVH.test.js

When using the `MeshBVH` constructor with the `onProgress` callback provided in the `options` dictionary: there's currently no point in execution at which it gets called with `1.0` to signify the true finalization of the building process.
The matter is: we may get values nearing `1.0` going as high as something like `9.9445486` if the total amount of triangles allows it, but when the faces are too few we will have trouble determining a reasonable threshold to consider that the progression has reached it's peak.
Let's assume we have a geometry of only two triangles (a quad, typically), then the highest value provided by the `progress` argument will likely by something like `0.5` and we will never get to (or near) `1.0` at any point, so even using something like `progress > 0.9` for …

Added final onProgress call on full MeshBVH building completion

---

src/index.d.ts
test/MeshBVH.test.js

👋 noticed that the `computeBoundsTree` extension method Typescript description doesn't denote that `MeshBVH` is returned. Added it to the description file and added a test for regressions.

Add return type for computeBoundsTree

---

example/edgeProjection.html
example/edgeProjection.js
example/utils/edgeUtils.js
package-lock.json
package.json
src/math/ExtendedTriangle.js

**TODO**
- ~Fix NaNs~
- ~check BVH bounds~
- ~Improve edge geometry generation (round to floor for hash?)~
- ~Reduce memory overhead~
- Time each step overall
- End shapecast traversal even earlier?
- Add a "regenerate" button
- Add a rotation configuration
- Add model toggle
- Display generation time
- Simplify use

Edge projection demo

---

src/core/MeshBVH.js
src/core/buildFunctions.js

Initial pass at trying to add support for normalized attributes to `three-mesh-bvh`, to address #448. I only found a single instance in the code of an obvious, direct position attribute array access, so I changed it to use the setter. I'm assuming that `geometry.index` will never be normalized, so didn't touch any direct array accesses for that.
With this change, `shapecast` worked again with my small examples I'd created to debug this issue. I didn't yet test raycasting, or any other feature. All unit tests continue to pass.
The `MeshBVHVisualizer` is still broken, and doesn't display at all on meshes with normalized position attributes. I also still don't have as complete of an idea of how `three-mesh-bvh`'s internals work as I like, so any feedback or pointers are welcome. I also have …

Support normalized attributes

---

README.md
example/gpuPathTracingSimple.js
example/sdfGeneration.html
example/sdfGeneration.js
example/utils/GenerateSDFMaterial.js
example/utils/RayMarchSDFMaterial.js
example/utils/RenderSDFLayerMaterial.js
example/utils/RenderSDFMaterial.js
package-lock.json
package.json
src/gpu/shaderFunctions.js
src/utils/StaticGeometryGenerator.js

Fix #348 
Related to #411 
**TODO**
- ~gpu / cpu toggle~
- ~margin adjustment~
- ~extract barycoord, face indices, face normal, distance~
- pick water-tight model
- raymarching
- distance adjustment
- remove need to read the bounds texture multiple times per box
- try skipping adding the bound to the stack if it's outside the current closest distance
- add normal extraction for inside / outside determination

Add gpu distance to point functions

---

example/skinnedMesh.js

`meshes` array seems unused and is confusing at first read (I thought this how the geometry is being initialized)

Remove unused variable from SkinnedMesh example

---

.github/workflows/benchmark-report.yml
benchmark/make-benchmark-log.js
benchmark/utils.js
src/core/MeshBVH.js
src/core/build/buildTree.js
src/core/build/computeBoundsUtils.js
src/core/build/geometryUtils.js
src/core/build/sortUtils.js
src/core/cast/intersectsGeometry.js
src/core/cast/raycast.js
src/core/cast/raycastFirst.js
src/gpu/MeshBVHUniformStruct.js
src/utils/GeometryRayIntersectUtilities.js
src/utils/TriangleUtilities.js
src/workers/generateAsync.worker.js
test/MeshBVH.test.js
test/RandomRaycasts.test.js
test/RandomRaycastsRepro.test.js
test/ShapeCasts.test.js

Related to #294 
**TODO**
- figure out option name, indirect field
- tests
- write more
- test / fix bvhcast
- benchmark
- documentation

Add indirect buffer

---

.gitignore
src/core/MeshBVHNode.js
src/core/build/buildTree.js
src/core/build/buildUtils.js
src/core/build/computeBoundsUtils.js

Buildtree updates

---

src/core/MeshBVH.js
test/MeshBVH.serialize.test.js

Related to https://github.com/gkjohnson/three-mesh-bvh/issues/663#issuecomment-2108369387
Fix BVH failing when deserializing an indirect buffer.

Fix indirect bvh serialization

---

src/core/MeshBVH.js

Hi I found a bug in constructor of MeshBVH.js
```ts
//previous
// In constructor this._indirectBuffer initialized null
// then this.resolveTriangleIndex use the latter of conditional operator 
// result of this.resolveTriangleIndex(i) returns i, even indirect is true
this.resolveTriangleIndex = this._indirectBuffer ? i => this._indirectBuffer[ i ] : i => i;
//fixed
this.resolveTriangleIndex = options.indirect ? i => this._indirectBuffer[ i ] : i => i;
```
this bug affects three-mesh-pathtracer
[scenario] initialize pathtracer => disable pathtracer => move model => enable pathtracer
previous version
https://github.com/gkjohnson/three-mesh-bvh/assets/108255990/18428557-8969-4433-841b-22b737fd87e8
For your Information log
P.S : always thanks fast feedback & amazing library

fix resolveTriangleIndex from wrong condition

---

src/utils/ExtensionUtilities.js
test/RandomRaycasts.test.js

Fix #671
Based on #673 
cc @agargaro I made some of the remaining changes requested from #673 - let me know how it looks and I'll merge and publish!

InstancedMesh raycast fix

---

src/utils/ExtensionUtilities.js
test/RandomRaycasts.test.js

I fixed the problem related to `getScaleWorld` and added tests. 
I need to clean up the code, but can you tell me if the `InstancedMesh` tests are okay? 
Shall I add tests on `BatchedMesh` too? (after https://github.com/mrdoob/three.js/pull/28462)
related #671

Fix `InstancedMesh` raycast

---

.gitignore
README.md
src/core/MeshBVH.js
src/core/build/buildTree.js
src/core/build/geometryUtils.js
src/index.d.ts
test/MeshBVH.options.test.js

- Adds a new range option that acts "as drawRange"
- Should allow multiple BVH on the same geometry with different ranges (useful for Three BatchedMesh)
Closes #513

feat: add range option to MeshBVH

---

src/index.d.ts

Fixes #682.
`three/src` should never be referenced in library code, but referencing the public export sidesteps the issue entirely.
`.js` file extensions are required when referencing source code, such as examples, but this can create its own issues (e.g., https://github.com/mrdoob/three.js/issues/24593).

Augment three instead for TypeScript ESM

---

README.md
example/batchedMesh.js
src/index.d.ts
src/index.js
src/utils/ExtensionUtilities.js
test/RandomRaycasts.test.js
test/TypescriptImportTest.ts

I thought about this a bit more and decided to restructure the batched mesh bvh computation functions. cc @agargaro - let me know what you think!
- Update the compute and dispose bounds tree functions for batched mesh to be searate
- Update functions to take an "index" argument so only a single bvh can be generated or removed
- Update colors for the example so it's more distinct from the raycast one:

Adjusted batched mesh bvh computation functions

---

README.md
src/objects/MeshBVHHelper.js

Fix #701
Adds `MeshBVHHelper.objectIndex` to support displaying a BVH for an individual BVH in an InstancedMesh or BatchedMesh.
cc @agargaro

MeshBVHHelper: Update BVH Helper for instances and batching

---

src/utils/ExtensionUtilities.js

Two questions:
1) It's necessary to create a way to get instances in use count (drawInfo.length). Is an `instancesCount` getter okay?
2) The method `getVisibleAt` and property `instancesCount` (and other future methods) , may not exist if the user is using an older version of three.js. How would you prefer to proceed? 
Adding these methods to `BatchedMesh.prototype`? 
Change the minimum version of three.js?

AcceleratedBatchedMeshRaycast: use `getVisibleAt` instead of `drawInfo` object

---

example/batchedMesh.js

related: #709 
This is the quickest way to fix the example, however I don't know if the most correct one.
This condition was alway `false` after change `splitStrategy`, and the BVH was no longer rebuilt.

BatchedMesh raycasting example: fix `splitStrategy` param

---

src/utils/ExtensionUtilities.js

I tried the fix you proposed and it works.
I tested by installing in this repo `three r151` which of course initially threw exception.
```js
import { Ray, Matrix4, Mesh, Vector3, Sphere, REVISION } from 'three';
import * as THREE from 'three';
```
Do you think these imports are okay? 
Or would you prefer to just use `import * as THREE from 'three';`?
related: #711

Fix `BatchedMesh` import `three r157-`

---

example/sdfGeneration.js
example/utils/GenerateSDFMaterial.js

This PR addresses the findings of https://github.com/gkjohnson/three-mesh-bvh/pull/705 by adding a CPU workaround to the flaky insided-ness check of the SDF generation.
It doesn't seem like the GPU SDF Generation works on Windows (Chrome AND Firefox) right now, so I've tried to add it while testing on my iOS device... but it seems like adding the raycast function crashes the renderer in my iOS device and I can't access any error messages from Windows😅

Make SDF Generation more Robust

---

.github/workflows/node.js.yml

Following up on your [request](https://github.com/gkjohnson/three-mesh-bvh/issues/711#issuecomment-2340498304) to add different versions of `three` to your CI pipeline. [Looks like it still doesn't work](https://github.com/dmurvihill/three-mesh-bvh/actions/runs/11046423591/job/30685724723) on 0.158.

Test on different versions of three

---

src/utils/ExtensionUtilities.js

Fix for #726 
Replaces #727 
Continue to use the private members since there's otherwise no way to know which items on deleted or not.

Fixes for batched mesh

---

README.md
example/utils/GenerateSDFMaterial.js
src/gpu/glsl/bvh_distance_functions.glsl.js

Recently I needed to find a closest mesh to the point on the gpu. It was pretty fast, considering the complexity. But it could be faster, if we allowed setting lower starting closestDistanceSquared thus skipping a lot of useless variants. Also, this would allow finding distances farther than 100000 (if this could in fact happen at all)
The change will not disrupt existing usage, but add a new possibility for situational performance improvement.
If you are ok with the change, should I document this somewhere? I couldn't find explicit documentation for shader function

Extend _bvhClosestPointToPoint to accept maxDistance

---

example/src/computeSelectedTriangles.js
example/utils/math/pointRayCrossesSegments.js

When the lasso shape is jagged along the right edge, this code will now still detect that a bounding box is completely inside it, optimizing the computation of selected triangles.
Follow-up to #738

Optimize the detection of the lasso containing bounds

---

src/utils/ThreeRayIntersectUtilities.js
test/Utils.geometryUtils.test.js

I've tried to align return values with threejs. Intersecting a degenerate triangle with:
- three.js <= 159 - returns zero-ed attributes
- 159 < three.js < 169 - returns null attributes
- three.js >= 169 - returns zero-ed attributes
Also moved `Triangle.getBarycoord` inside the if statement as it was only needed with three.js >= 169. Or did I miss something?
There's also `getTriangleHitPointInfo` which does not suffer from NPE, but also always return zero-ed attributes already. I didn't feel it was necessary to be changed as it does not have a three.js analog (or I didn't find one)
Fixes #724

Fix NPE when intersecting degenerate triangle

---

README.md

This small PR fixes the `bvh_struct_definitions.glsl.js` reference in `README.md`. It also fixes a few typos along the way.

Update `bvh_struct_definitions.glsl.js` source
