gkjohnson/three-mesh-bvh

README.md
benchmark/run-benchmark.js
benchmark/utils.js
example/boundsTree.js
package.json
src/BVHConstructionContext.js
src/Constants.js
src/MeshBVH.js
src/index.js
test/test.js

@mquander 
Fix #51 
Fix #52
- Added test for and fixed the maxDepth bug
- Export functions from the index instead of modifying the THREE prototypes directly
- Rename to `three-mesh-bvh`
- Rename `maxLeafNodes` to `maxLeafTris`

Export updates, bug fixes

---

src/BVHConstructionContext.js

Fix bug in average split strategy

---

README.md
benchmark/run-benchmark.js
src/MeshBVH.js
test/test.js

Fix #47 
- Set default `maxDepth` to be 40
- add warning log if it's reached
- add option to suppress warnings

Add default for max depth option

---

src/Utils/ThreeIntersectionUtilities.js

This is implemented almost identically to what we had before. [It's been in three.js since r96](https://github.com/mrdoob/three.js/commit/c48d55fc3a11004edb2a8837373f77661cc838b8).

Use Triangle.getUV in checkIntersection

---

src/MeshBVHNode.js
test/MeshBVH.test.js

Fix #91 
- Add tests for `distanceToGeometry` and `distanceToPoint`
- Fix bug in `distanceToGeometry`

Distance tests

---

src/BVHConstructionContext.js

Resolves #105. When I ran the benchmark this didn't really seem to move the needle in a way indistinguishable from noise -- perhaps any gain from faster partitioning is being given back in slightly slower bounds calculation. I still like this change for purposes of simpler code and more precise splits with the CENTER strategy, and it's nice to not allocate an extra geometry-sized buffer, too.

Use center of bounds rather than centroids

---

src/MeshBVHNode.js

avoid uglify error in strict mode

refactor: inline triangleCallback

---

README.md
babel.config.js
benchmark/run-benchmark.js
benchmark/utils.js
example/raycast.js
package-lock.json
package.json
src/MeshBVH.js
src/MeshBVHVisualizer.js
src/Utils/Debug.js
src/buildFunctions.js
src/castFunctions.js
test/MeshBVH.test.js

Fix #128.
Add support for progressive tree generation as casts necessitate.

Lazy construction

---

src/MeshBVH.js

Pack the buffer data in the serialize function more

---

README.md
example/asyncGenerate.js
src/workers/GenerateMeshBVHWorker.js
src/workers/MeshBVHGenerationWorker.js
src/workers/generateAsync.js

Fix #152
Improves time to generation completion.

Make reusable worker generation class

---

.github/workflows/node.js.yml
.travis.yml
README.md

Add Github Actions CI

---

example/physics.html
example/selection.html
example/selection.js
example/shapecast.html
src/castFunctions.js
src/castFunctionsBuffer.js
test/ShapeCasts.test.js

Fix #166
- centroid selection is still very fast without bounds tree.
- sensible lasso selection with full triangle intersection can improve 5 - 100 times.
- much less improvement if not degradation with lasso selection that covers the whole model.

Lasso example

---

test/RandomRaycasts.test.js

Make random tests random again, improve reproduce-ability

---

benchmark/run-benchmark.js
example/randomSampleDebug.html
example/randomSampleDebug.js
src/castFunctions.js
src/castFunctionsBuffer.js
test/RandomRaycastsRepro.test.js

Reliable raycast failure tests

---

package-lock.json
package.json
src/Utils/ThreeIntersectionUtilities.js

update to v0.126.1

---

CONTRIBUTING.md

They're pretty straightforward, but it's nice to have this stuff written down.
(Sorry for the auto-formatting changes!)

Add developer setup instructions

---

src/workers/generateAsync.js

^ Should this instead be removed here and from main readme?

[workers] - fix name in warning

---

CHANGELOG.md
README.md
benchmark/run-benchmark.js
example/sculpt.js
src/MeshBVH.js
src/buildFunctions.js
src/castFunctions.js
src/castFunctions.template.js
src/workers/GenerateMeshBVHWorker.js
test/MeshBVH.test.js

Add getBoundingBox function

---

.github/workflows/node.js.yml
CHANGELOG.md
README.md
example/characterMovement.js
example/collectTriangles.js
example/physics.js
example/sculpt.js
example/selection.js
src/MeshBVH.js
src/Utils/BufferNodeUtils.js
src/castFunctions.js
src/castFunctions.template.js
test/ShapeCasts.test.js

Fix #218
Fix #173
**TODO**
- Should afford some small optimizations for collect triangles, possibly other examples

Shapecast update

---

CHANGELOG.md
README.md
example/collectTriangles.js
example/sculpt.js
example/selection.js
src/MeshBVH.js
src/Utils/BufferNodeUtils.js
test/ShapeCasts.test.js

Shapecast intersectTriangle signature update

---

README.md
benchmark/run-benchmark.js
example/collectTriangles.js
example/sculpt.js
src/MeshBVH.js
src/castFunctions.js
src/castFunctions.template.js

Optimize refit

---

example/characterMovement.js

Fix sliding character in player movement demo

---

src/castFunctions.template.js

Remove unused arguments from shapecast

---

scripts/generate-cast-functions.js
src/castFunctions.template.js

Clean up cast functions

---

benchmark/run-benchmark.js
scripts/generate-cast-functions.js
src/MeshBVH.js
src/Utils/OrientedBox.js
src/Utils/TriangleUtils.js

- Fix bug in distanceToGeometry resulting in an incorrect distance likely being returned which results in significantly degraded performance.
- Add BVH fast path to distanceToGeometry function which has overall better performance.
Related to #82. Triangle distance check performance could probably be improved.

Add BVH path to distanceToGeometry

---

src/MeshBVH.js
src/buildFunctions.js

related to #147
Adjust `refit` function and `computeTriangleBounds` function to support interleaved attributes

Position Buffer Attribute updates

---

README.md
src/MeshBVH.js
test/MeshBVH.test.js
test/RandomRaycasts.test.js

Add InterleavedBufferAttribute support for position attributes

---

example/raycast.js
src/MeshBVHVisualizer.js

Improve visualizer update performance

---

src/Utils/SeparatingAxisTriangle.js

Slightly simplify the update in SeparatingAxisTriangle
**TODO**

SeparatingAxisTriangle: simplify calls to update

---

README.md
src/MeshBVHVisualizer.js

MesBVHVisualizer: Add support of display bounds as solid meshes

---

README.md
benchmark/run-benchmark.js
example/inspector.html
example/inspector.js
src/Utils/Debug.js

Fix #287 
**TODO**
- Requires ability to clear integer buffer in three.js

Add inspector demo

---

example/asyncGenerate.js
example/collectTriangles.js
example/distancecast.js
example/randomSampleDebug.js
example/raycast.js
example/shapecast.js
test/MeshBVH.test.js

Clean up example imports

---

example/edgeIntersect.js
package.json

make edge intersect demo faster

---

README.md
src/core/MeshBVH.js

Fixes #328 
I think it is solved simply with these two lines.

ClosestPointToGeometry, ClosestPointToPoint: Return null if distance is outside of min, max distance range

---

README.md
benchmark/run-benchmark.js
example/characterMovement.js
example/clippedEdges.js
example/physics.js
example/sculpt.js
src/core/MeshBVH.js

Fix #308 
Update refit function to take a single argument just describing traversed nodes.

Simplify refit function API

---

README.md
src/core/MeshBVH.js
src/core/buildFunctions.js
src/index.d.ts
src/workers/GenerateMeshBVHWorker.js
src/workers/generateAsync.worker.js
test/MeshBVH.test.js

Add worker onProgress callback

---

src/index.d.ts

@minitoine referencing another answer in your linked SO answer I've modified the index.d.ts answer to be simpler. Does this solution make sense / work for you?

index.d.ts: Switch to use union types

---

README.md
src/workers/GenerateMeshBVHWorker.js
src/workers/generateAsync.worker.js

This should help this issue:
https://github.com/gkjohnson/three-mesh-bvh/issues/392#issuecomment-1072703011

Groups in worker

---

CHANGELOG.md
example/cpuPathTracing.js
src/workers/GenerateMeshBVHWorker.js

Terminate->dispose

---

src/utils/StaticGeometryGenerator.js

StaticGeometryGenerator: small simplification

---

example/skinnedMesh.js
example/voxelize.html
example/voxelize.js

Fix #412 
**TODO**
**Use Cases**
- Light probe placement
- Retopology
- Physics particle sim
- Navigation network

Add voxelization demo

---

src/workers/generateAsync.worker.js

There is no `global` variable. This fixes a `variable not defined` exception.

Fixes the `global is not defined` bug.

---

example/clippedEdges.js

Fix: Fix clippedEdges example, missing intersecting edges

---

example/triangleIntersect.js
src/math/ExtendedTriangle.js

Intersection fix

---

src/core/MeshBVH.js

Fix bvhcast bug

---

src/math/ExtendedTriangle.js

Fix for https://github.com/gkjohnson/three-bvh-csg/issues/36

Improve IntersctsTriangle further

---

src/math/ExtendedTriangle.js
src/math/MathUtilities.js

to fix two question of  https://github.com/gkjohnson/three-mesh-bvh/issues/444

fix case with one point intersection and closestPointLineToLine

---

example/selection.js

Related to https://github.com/gkjohnson/three-mesh-bvh/issues/389#issuecomment-1254154605

Selection Example: Add support for visible triangle selection only

---

example/asyncGenerate.js
example/collectTriangles.js
example/cpuPathTracing.js
example/distancecast.js
example/edgeIntersect.js
example/gpuPathTracingSimple.js
example/physics.js
example/randomSampleDebug.js
example/raycast.js
example/selection.js
example/shapecast.js
example/voxelize.js
package-lock.json
package.json
src/gpu/VertexAttributeTexture.js
test/MeshBVH.test.js
test/RandomRaycasts.test.js
test/RandomRaycastsRepro.test.js
test/ShapeCasts.test.js
test/VertexAttributeTexture.test.js

Fix case with new three.js by forcing normalization

---

src/index.d.ts
src/math/OrientedBox.js

OrientedBox: Remove box3 inheritance

---

example/triangleIntersect.js
src/math/ExtendedTriangle.js
test/IntersectionUtils.test.js

Fix triangle intersect

---

example/edgeProjection.js
example/selection.js
src/core/buildFunctions.js
src/utils/ArrayBoxUtilities.js
src/utils/StaticGeometryGenerator.js
src/workers/GenerateMeshBVHWorker.js

Figures I'll have a typo in the commit message...
The `// clockwise or counterclockwise` fix is very questionable

Some very minor typos fixed

---

example/skinnedMesh.js
src/utils/StaticGeometryGenerator.js

Improve StaticGeometryGeneration perf with unchanging mesh

---

src/workers/GenerateMeshBVHWorker.js
src/workers/generateAsync.worker.js

bugfix#523

---

package-lock.json
package.json
src/utils/StaticGeometryGenerator.js
src/utils/ThreeRayIntersectUtilities.js
src/utils/TriangleUtilities.js

Upgrade three

---

src/core/buildFunctions.js
src/utils/ArrayBoxUtilities.js
test/MeshBVH.test.js

Fix root bounding box

---

src/math/ExtendedTriangle.js

Reuse plane intersect logic

---

src/math/ExtendedTriangle.js
test/IntersectionUtils.test.js

Fix triangle x triangle intersect error

---

src/core/bvhcast.js
src/core/castFunctions.js

Next:
- More cast cleanup functions to make it easier to adjust and modify for #294 
- See if we can move some logic outside of the cast function

Small cleanup

---

src/core/build/geometryUtils.js
test/MeshBVH.options.test.js
test/MeshBVH.test.js
test/MeshBVHUniformStruct.test.js

Fix #587 
**TODO**
- Add tests for indirect and non indirect cases

Respect draw range when making the BVH

---

src/utils/ThreeRayIntersectUtilities.js
test/MeshBVH.options.test.js

**TODO**
- Benchmark w/ and w/o index condition

Fix indirect raycast

---

CHANGELOG.md
README.md
example/physics.js
src/objects/MeshBVHHelper.js

Add bvh option to MeshBVHHelper signature

---

src/gpu/glsl/bvh_distance_functions.glsl.js
src/gpu/glsl/bvh_ray_functions.glsl.js
src/gpu/glsl/bvh_struct_definitions.glsl.js
src/gpu/glsl/common_functions.glsl.js

Fix #612 
**Functions**
- ~distanceToTriangles~
- ~distanceSqToBVHNodeBoundsPoint~
- ~bvhClosestPointToPoint~
- ~intersectTriangles~
- ~intersectsBVHNodeBounds~
- ~bvhIntersectFirstHit~

Remove passing of bvh structs to functions

---

src/gpu/glsl/bvh_distance_functions.glsl.js
src/gpu/glsl/bvh_ray_functions.glsl.js
src/gpu/glsl/common_functions.glsl.js

Related to #621
Related to #619

Clean up, investigate stack depth

---

example/gpuPathTracing.js
example/sdfGeneration.js

Fix ios issues

---

src/core/build/buildTree.js
src/core/build/computeBoundsUtils.js
test/MeshBVH.test.js

Merge some logic between single root and multiple roots
**TODO**
- perf test

Small built tree cleanup

---

src/debug/Debug.js
test/MeshBVH.options.test.js

Fix bounds validation for indirect bvh

---

src/utils/StaticGeometryGenerator.js

StaticGeometryGenerator: Add support for inverted geometry

---

src/core/cast/bvhcast.js

fix index of otherRoots[i] to otherRoots[j]

fix index of otherRoots[i] to otherRoots[j]

---

README.md
example/batchedMesh.html
example/batchedMesh.js
package-lock.json
package.json
src/index.d.ts
src/index.js
src/utils/ExtensionUtilities.js
test/RandomRaycasts.test.js
test/TypescriptImportTest.ts

I wrote a working prototype, but obviously a few things should be changed and tests added.
The example needs to be changed, I only used it to test. Which example would you like to have?

Add BatchedMesh accelerated raycast support

---

src/objects/MeshBVHHelper.js

Ensure we don't break with box3 precise setFromObject

---

package.json
src/utils/ExtensionUtilities.js

Update three.js version to 158 so BatchedMesh is supported

---

src/index.d.ts

Fix ts definitions for raycastFirst
